VidhyasDietERP/urls.py
from django.urls import path, include

from django.contrib import admin
# from vidhyas_api.views import ObtainAuthTokenView

urlpatterns = [
    path('admin/', admin.site.urls),            # default admin
    path('api/', include("vidhyas_api.urls")),  # include api
    path('', include("user_authentication.urls")),   # include auth
    path('', include("customer.urls")),   # include auth
    path('', include("humanresource.urls")),   # include auth
    path('', include('index.urls')),             # include index
    path('', include('inquiry.urls')),             # include inquiry
    path('', include('registration.urls')),             # include registration
    path('', include('account.urls')),             # include account_list
    path('', include('diet.urls')),             # include diet
    path('', include('todo.urls')),             # include diet
]

customer/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from customer.views import (DietPlanAPI, DietPlanDetails, CustomerAPI, CustomerDetails, customer_list, add_customer,
                            edit_customer, trash_customer, customer_detail, vidhyas_package, delete_vidhyas_package)

app_name = 'customer'

urlpatterns = [

    path('api/diet_plan', DietPlanAPI.as_view(), name='DietPlanAPI'),
    path('api/diet_plan/<int:pk>', DietPlanDetails.as_view(), name='DietPlanDetailsApi'),
    path('api/customer', CustomerAPI.as_view(), name='CustomerAPI'),
    path('api/customer/<int:pk>', CustomerDetails.as_view(), name='CustomerDetailsApi'),

    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer_list/', customer_list, name='customer_list'),
    path('add_customer/', add_customer, name='add_customer'),
    path('edit_customer/<int:pk>/', edit_customer, name='edit_customer'),
    path('trash_customer/', trash_customer, name='trash_customer'),
    path('vidhyas_package/', vidhyas_package, name='vidhyas_package'),
    path('vidhyas_package/<int:pk>', vidhyas_package, name='edit_vidhyas_package'),
    path('delete_vidhyas_package/', delete_vidhyas_package, name='delete_vidhyas_package'),
]

diet/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from diet.views import (create_logbook_and_stats, body_composition, create_diet_plan_new, create_diet_plan,
                        edit_diet_plan, diet_plan_list, diet_plan_print_nepali, diet_plan_print_english,
                        diet_plan_trash, diet_plan_preview,chart)

app_name = 'diet'

urlpatterns = [
    path('create_logbook_and_stats/', create_logbook_and_stats, name='create_logbook_and_stats'),
    path('create_logbook_and_stats/<int:pk>/', create_logbook_and_stats, name='edit_logbook_and_stats'),

    path('bmi/', body_composition, name='bmi'),
    path('bmi/<int:pk>/', body_composition, name='edit_bmi'),

    # path('diet_plan/', create_or_edit_diet_plan, name='create_diet_plan'),
    # path('diet_plan/<int:pk>/', create_or_edit_diet_plan, name='edit_diet_plan'),

    path('diet_plan_preview/<int:pk>/', diet_plan_preview, name='diet_plan_preview'),
    path('create_diet_plan_new/', create_diet_plan, name='create_diet_plan'),
    path('diet_plan/<int:pk>/edit/', edit_diet_plan, name='edit_diet_plan'),
    path('diet_plan/new/<int:customer_id_pk>/', create_diet_plan_new, name='create_diet_plan_new'),
    path('diet_plan_list/', diet_plan_list, name='diet_plan_list'),
    path('diet_plan_print_nepali/<int:pk>/', diet_plan_print_nepali, name='diet_plan_print_nepali'),
    path('diet_plan_print_english/<int:pk>/', diet_plan_print_english, name='diet_plan_print_english'),
    path('diet_plan_trash/', diet_plan_trash, name='diet_plan_trash'),


    path('chart/<int:client_id>/', chart, name='chart'),

]

diet/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from customer.models import Customer
from diet.form import LogBookForm, BMIForm, DietPlanForm
from diet.models import LogBook, BodyComposition, DietPlan

# views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib import messages


def create_logbook_and_stats(request, pk=None):
    if pk:
        logBook = get_object_or_404(LogBook, pk=pk)
    else:
        logBook = None

    if request.method == 'POST':
        if logBook:
            form = LogBookForm(request.POST, instance=logBook)
        else:
            form = LogBookForm(request.POST, user=request.user)

        if form.is_valid():
            logbook_instance = form.save()
            logbook_instance.create_or_update_customer_stats()  # Ensure customer stats are updated
            messages.success(request, 'LogBook entry saved successfully.')
            return redirect('diet:create_logbook_and_stats')  # Redirect to the form page after saving
    else:
        if logBook:
            form = LogBookForm(instance=logBook)
        else:
            form = LogBookForm(user=request.user)

    context = {
        'form': form,
        'logbook_entries': LogBook.objects.all().order_by('date')  # To list all logbook entries if needed
    }
    return render(request, 'diet/log_book/logbook.html', context)


def body_composition(request, pk=None):
    if pk:
        bodyComposition = get_object_or_404(BodyComposition, pk=pk)
    else:
        bodyComposition = None

    if request.method == 'POST':
        if bodyComposition:
            form = BMIForm(request.POST, instance=bodyComposition)
        else:
            form = BMIForm(request.POST, user=request.user)

        if form.is_valid():
            bodyComposition_instance = form.save()
            bodyComposition_instance.create_customer_stats()  # Ensure customer stats are updated
            messages.success(request, 'BMI  entry saved successfully.')
            return redirect('diet:bmi')  # Redirect to the form page after saving
    else:
        if bodyComposition:
            form = BMIForm(instance=bodyComposition)
        else:
            form = BMIForm(user=request.user)

    context = {
        'form': form,
        'bodyComposition': BodyComposition.objects.all().order_by('recorded_at')
        # To list all logbook entries if needed
    }
    return render(request, 'diet/body_composition/body_composition.html', context)


def create_diet_plan_new(request, customer_id_pk):
    customer = get_object_or_404(Customer, pk=customer_id_pk)

    if request.method == 'POST':
        form = DietPlanForm(request.POST)
        if form.is_valid():
            diet_plan = form.save(commit=False)
            diet_plan.customer = customer
            diet_plan.created_by = request.user
            diet_plan.save()
            return redirect('customer:customer_detail', pk=customer_id_pk)
    else:
        form = DietPlanForm(initial={'customer': customer, 'created_by': request.user, 'created_date': timezone.now()})

    context = {
        'form': form,
        'customer': customer,
        'created_by': request.user,
        'created_date': timezone.now()
    }

    return render(request, 'diet/diet_plan/diet_plan_form.html', context)


def create_diet_plan(request):
    if request.method == 'POST':
        print(request.POST)
        form = DietPlanForm(request.POST, user=request.user)
        if form.is_valid():
            diet_plan = form.save(commit=False)
            diet_plan.created_by = request.user
            diet_plan.save()
            messages.success(request, 'Diet Plan created successfully.')
            return redirect('diet:diet_plan_list')
        else:
            print(form.errors)
    else:
        form = DietPlanForm(user=request.user)
    return render(request, 'diet/diet_plan/diet_plan_form.html', {'form': form})


def edit_diet_plan(request, pk):
    diet_plan = get_object_or_404(DietPlan, pk=pk)
    if request.method == 'POST':
        form = DietPlanForm(request.POST, instance=diet_plan, user=request.user)
        if form.is_valid():
            form.cleaned_data['customer'] = diet_plan.customer
            form.save()
            messages.success(request, 'Diet Plan updated successfully.')
            return redirect('diet:diet_plan_list')
        else:
            print(form.errors)
    else:
        form = DietPlanForm(instance=diet_plan, user=request.user)
    return render(request, 'diet/diet_plan/diet_plan_form.html', {'form': form})


def diet_plan_list(request):
    diet_plan = DietPlan.objects.order_by('created_date').filter(trashed=False)
    customer = Customer.objects.all()
    context = {
        'diet_plans': diet_plan,
        'customers': customer
    }
    return render(request, 'diet/diet_plan/diet_plan_list.html', context)


def diet_plan_print_nepali(request, pk):
    diet_plan = DietPlan.objects.get(id=pk)
    context = {
        'diet_plan': diet_plan,
    }
    return render(request, 'diet/diet_plan/vidhyas_diet_plan_nepali.html', context)


def diet_plan_print_english(request, pk):
    diet_plan = DietPlan.objects.get(id=pk)
    context = {
        'diet_plan': diet_plan,
    }
    return render(request, 'diet/diet_plan/vidhyas_diet_plan_english.html', context)


def diet_plan_trash(request):
    id = request.POST.get('trash_id')
    diet_plan = DietPlan.objects.get(id=id)
    diet_plan.trashed = True
    print('true')
    diet_plan.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def diet_plan_preview(request,pk):
    diet_plan = DietPlan.objects.get(id=pk)
    context = {
        'diet_plan': diet_plan,
    }
    return render(request, 'diet/diet_plan/vidhyas_diet_plan_preview.html', context)


def chart(request,client_id):
    log_entries = LogBook.objects.filter(client_id=client_id).order_by('date')
    dates = [entry.date.strftime('%Y-%m-%d') for entry in log_entries]
    before_weights = [entry.before_weight for entry in log_entries]
    after_weights = [entry.after_weight for entry in log_entries]

    context = {
        'dates': dates,
        'before_weights': before_weights,
        'after_weights': after_weights
    }
    return render(request, 'diet/logbook_chart.html', context)

templates/diet/diet_plan/diet_plan_list.html
{% extends 'diet/diet_base.html' %}
{% load static %}
{% block page_css %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/select.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/dataTables.dataTables.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
    <style>
        .dataTables_wrapper .top, .dataTables_wrapper .bottom {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
        }

        .dataTables_wrapper .dataTables_length,
        .dataTables_wrapper .dataTables_filter,
        .dataTables_wrapper .dataTables_paginate,
        .dataTables_wrapper .dataTables_info {
            margin: 0;
        }

        .dataTables_wrapper .dt-buttons {
            margin-left: auto;
        }
    </style>
{% endblock page_css %}

{% block sub-content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div>
    </section>


    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Diet Plan List</h3>
                        </div>
                        <div class="card-body">
                            <table id="dtable" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Date | Created By</th>
                                    <th>Client</th>
                                    <th>Day</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for diet_plan in diet_plans reversed %}
                                    <tr>
                                        <td></td>
                                        <td>{{ diet_plan.created_date|date:"d/m/Y " }}
                                            | {{ diet_plan.created_by }}</td>
                                        <td>{{ diet_plan.customer }}</td>
                                        <td>{{ diet_plan.day }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button"
                                                        class="btn btn-block btn-outline-secondary dropdown-toggle"
                                                        data-toggle="dropdown">Action
                                                </button>
                                                <div class="dropdown-menu" role="menu">
                                                    <a class="dropdown-item"
                                                       href="{% url 'customer:customer_detail' diet_plan.customer.id %}">Customer
                                                        Details</a>   <a class="dropdown-item"
                                                       href="{% url 'diet:diet_plan_preview' diet_plan.id %}">
                                                    Preview
                                                        Diet Chart</a>
                                                    <a class="dropdown-item"
                                                       href="{% url 'diet:edit_diet_plan' diet_plan.pk %}">Edit</a>
                                                    <a class="dropdown-item"
                                                       href="{% url 'diet:diet_plan_print_nepali' diet_plan.pk %}"
                                                       target="_blank">Print Nepali</a>
                                                    <a class="dropdown-item"
                                                       href="{% url 'diet:diet_plan_print_english' diet_plan.pk %}"
                                                       target="_blank">Print
                                                        English</a>
                                                      <a class="dropdown-item"
                                                       href="#" data-toggle="modal"
                                                       data-target="#trash_transaction"
                                                       data-id="{{ diet_plan.id }}">Trash
                                                      </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th>Date | Created By</th>
                                    <th>Client</th>
                                    <th>Day</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="trash_transaction">
        <div class="modal-dialog">
            <div class="modal-content bg-danger">
                <div class="modal-header">
                    <h4 class="modal-title">Trash Diet Plan</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form-horizontal" action="{% url 'diet:diet_plan_trash' %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <input type="hidden" id="trash_id" name="trash_id">
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-light">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock sub-content %}

{% block page_script %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-select/js/select.bootstrap4.min.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            var table = $('#dtable').DataTable({
                lengthMenu: [10, 20, 50, 100],
                responsive: true, lengthChange: false, autoWidth: false,
                columnDefs: [
                    {orderable: false, className: 'select-checkbox', targets: 0}
                ],
                select: {
                    style: 'multi',
                    selector: 'td:first-child'
                },
                dom: '<"top"fB>rt<"bottom"ilp><"clear">',
                buttons: [
                    {
                        text: 'Delete Selected',
                        className: 'btn btn-primary delete-selected',
                        action: function () {
                            var selectedRows = table.rows({selected: true}).data();
                            var ids = [];
                            for (var i = 0; i < selectedRows.length; i++) {
                                ids.push(selectedRows[i][1]); // Assuming the ID is in the second column
                            }
                            if (ids.length > 0) {
                                // Implement your delete logic here
                                console.log('Delete these IDs:', ids);
                                // Example: Make an AJAX call to delete
                                // $.post('/delete-url/', { ids: ids }, function(response) {
                                //     table.rows('.selected').remove().draw(false);
                                // });
                            } else {
                                alert('No rows selected');
                            }
                        },
                        enabled: false
                    },
                ]
            });

            table.on('select deselect', function () {
                var selectedRows = table.rows({selected: true}).count();
                table.button(0).enable(selectedRows > 0);
                if (selectedRows > 0) {
                    $('.delete-selected').show();
                } else {
                    $('.delete-selected').hide();
                }
            });

            $('.delete-selected').hide();
            $('.select2').select2();
        });

        $(function () {
            $('#trash_transaction').on('show.bs.modal', function (event) {
                document.getElementById("trash_id").value = $(event.relatedTarget).data('id');
            });
        });
    </script>
{% endblock page_script %}

templates/diet/diet_plan/diet_plan_preview_template.html
<!DOCTYPE html>
<html lang="ne">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>आहार परामर्श तालिका</title>
    <style>body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }

    .container {
        width: 90%;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .header-left {
        display: flex;
        align-items: center;
    }

    .logo {
        width: 50px;
        height: auto;
        margin-right: 10px;
    }

    h1 {
        font-size: 24px;
        margin: 0;
    }

    .header-right p {
        margin: 0;
    }

    h2, h3 {
        text-align: center;
        margin: 20px 0;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th, td {
        border: 1px solid #000;
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
    </style>
</head>
<body>
<div class="container">
    <header>

    </header>
    <h2>आहार परामर्श तालिका</h2>
    <p>प्रत्येक दिन खाना समूह द्वारा सेवा दिनु</p>
    <table>
        <thead>
        <tr>
            <th>अलु, गेडागुडी स्टाच</th>
            <th>तरकारी</th>
            <th>फलफूल</th>
            <th>मासु, अण्डा र अन्य मासु पदार्थ</th>
            <th>दूध र दूधका परिकारहरू</th>
            <th>बोसो र चिनी पदार्थहरू</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="6"></td>
        </tr>
        </tbody>
    </table>
    <h3>विहानको साज</h3>
    <table>
        <tbody>
        <tr>
            <td>सिङ रोटी (आटा, मकै, फापर, कोदो आदि)</td>
            <td></td>
        </tr>
        <tr>
            <td>सुक्का रोटी</td>
            <td></td>
        </tr>
        <tr>
            <td>जौको चिउरा</td>
            <td></td>
        </tr>
        <tr>
            <td>अण्डा (उबालेको)</td>
            <td></td>
        </tr>
        <tr>
            <td>उबालेको तरकारीहरू</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <h3>मध्य विहानको साज</h3>
    <table>
        <tbody>
        <tr>
            <td>काटेको फलफूल</td>
            <td></td>
        </tr>
        <tr>
            <td>दूध वा माछी</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <h3>साज</h3>
    <table>
        <tbody>
        <tr>
            <td>भात/रोटी/खाजा</td>
            <td></td>
        </tr>
        <tr>
            <td>सुक्का रोटी</td>
            <td></td>
        </tr>
        <tr>
            <td>दाल/गेडागुडी</td>
            <td></td>
        </tr>
        <tr>
            <td>तरकारी</td>
            <td></td>
        </tr>
        <tr>
            <td>साज/काँचो तरकारीहरू</td>
            <td></td>
        </tr>
        <tr>
            <td>मासु/तोफु/पनीर</td>
            <td></td>
        </tr>
        <tr>
            <td>माछा (हप्तामा एकपटक)</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <h3>मध्याह्नको साज</h3>
    <table>
        <tbody>
        <tr>
            <td>स्वादिष्ट</td>
            <td></td>
        </tr>
        <tr>
            <td>सुक्का रोटी/रोटी रोल</td>
            <td></td>
        </tr>
        <tr>
            <td>चिउरा</td>
            <td></td>
        </tr>
        <tr>
            <td>भुजा/मुड़ी/मकै</td>
            <td></td>
        </tr>
        <tr>
            <td>गेडागुडी</td>
            <td></td>
        </tr>
        <tr>
            <td>काँचो तरकारीहरू</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <h3>रातिको साज</h3>
    <table>
        <tbody>
        <tr>
            <td>भात/रोटी/खाजा</td>
            <td></td>
        </tr>
        <tr>
            <td>सुक्का रोटी</td>
            <td></td>
        </tr>
        <tr>
            <td>दाल/गेडागुडी</td>
            <td></td>
        </tr>
        <tr>
            <td>तरकारी</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <h3>क्यालोरी र ग्राममा दैनिक मापन लक्ष्य</h3>
    <table>
        <tbody>
        <tr>
            <td>क्यालोहाइड्रेड क्यालोरीमा</td>
            <td></td>
        </tr>
        <tr>
            <td>ग्राममा</td>
            <td></td>
        </tr>
        <tr>
            <td>प्रोटिन क्यालोरीमा</td>
            <td></td>
        </tr>
        <tr>
            <td>ग्राममा</td>
            <td></td>
        </tr>
        <tr>
            <td>बोसो क्यालोरीमा</td>
            <td></td>
        </tr>
        <tr>
            <td>ग्राममा</td>
            <td></td>
        </tr>
        <tr>
            <td>जम्मा क्यालोरी</td>
            <td></td>
        </tr>
        <tr>
            <td>व्यायाम तह</td>
            <td></td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>