VidhyasDietERP/urls.py
from django.urls import path, include

from django.contrib import admin
# from vidhyas_api.views import ObtainAuthTokenView

urlpatterns = [
    path('admin/', admin.site.urls),            # default admin
    path('api/', include("vidhyas_api.urls")),  # include api
    path('', include("user_authentication.urls")),   # include auth
    path('', include("customer.urls")),   # include auth
    path('', include("humanresource.urls")),   # include auth
    path('', include('index.urls')),             # include index
    path('', include('inquiry.urls')),             # include inquiry
    path('', include('registration.urls')),             # include registration
    path('', include('account.urls')),             # include account_list
    path('', include('diet.urls')),             # include diet
    path('', include('todo.urls')),             # include diet
]

customer/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from customer.views import (DietPlanAPI, DietPlanDetails, CustomerAPI, CustomerDetails, customer_list, add_customer,
                            edit_customer, trash_customer, customer_detail, vidhyas_package, delete_vidhyas_package)

app_name = 'customer'

urlpatterns = [

    path('api/diet_plan', DietPlanAPI.as_view(), name='DietPlanAPI'),
    path('api/diet_plan/<int:pk>', DietPlanDetails.as_view(), name='DietPlanDetailsApi'),
    path('api/customer', CustomerAPI.as_view(), name='CustomerAPI'),
    path('api/customer/<int:pk>', CustomerDetails.as_view(), name='CustomerDetailsApi'),

    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer_list/', customer_list, name='customer_list'),
    path('add_customer/', add_customer, name='add_customer'),
    path('edit_customer/<int:pk>/', edit_customer, name='edit_customer'),
    path('trash_customer/', trash_customer, name='trash_customer'),
    path('vidhyas_package/', vidhyas_package, name='vidhyas_package'),
    path('vidhyas_package/<int:pk>', vidhyas_package, name='edit_vidhyas_package'),
    path('delete_vidhyas_package/', delete_vidhyas_package, name='delete_vidhyas_package'),
]

diet/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from diet.views import (create_logbook_and_stats, body_composition, create_diet_plan_new, create_diet_plan,
                        edit_diet_plan, diet_plan_list, diet_plan_print_nepali, diet_plan_print_english,
                        diet_plan_trash, diet_plan_preview,chart)

app_name = 'diet'

urlpatterns = [
    path('create_logbook_and_stats/', create_logbook_and_stats, name='create_logbook_and_stats'),
    path('create_logbook_and_stats/<int:pk>/', create_logbook_and_stats, name='edit_logbook_and_stats'),

    path('bmi/', body_composition, name='bmi'),
    path('bmi/<int:pk>/', body_composition, name='edit_bmi'),

    # path('diet_plan/', create_or_edit_diet_plan, name='create_diet_plan'),
    # path('diet_plan/<int:pk>/', create_or_edit_diet_plan, name='edit_diet_plan'),

    path('diet_plan_preview/<int:pk>/', diet_plan_preview, name='diet_plan_preview'),
    path('create_diet_plan_new/', create_diet_plan, name='create_diet_plan'),
    path('diet_plan/<int:pk>/edit/', edit_diet_plan, name='edit_diet_plan'),
    path('diet_plan/new/<int:customer_id_pk>/', create_diet_plan_new, name='create_diet_plan_new'),
    path('diet_plan_list/', diet_plan_list, name='diet_plan_list'),
    path('diet_plan_print_nepali/<int:pk>/', diet_plan_print_nepali, name='diet_plan_print_nepali'),
    path('diet_plan_print_english/<int:pk>/', diet_plan_print_english, name='diet_plan_print_english'),
    path('diet_plan_trash/', diet_plan_trash, name='diet_plan_trash'),


    path('chart/<int:client_id>/', chart, name='chart'),

]

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('registration_list/', views.registration_list, name='registration_list'),
    path('registration_print/<int:registration_id>/', views.registration_print, name='registration_print'),
    path('inquiry_to_registration_form/', views.inquiry_to_registration_form, name='inquiry_to_registration_form'),
    path('inquiry_to_registration/', views.inquiry_to_registration, name='inquiry_to_registration'),
    path('trash_registration/', views.trash_registration, name='trash_registration'),
    path('edit_registration_form/', views.edit_registration_form, name='edit_registration_form'),
    path('edit_registration/', views.edit_registration, name='edit_registration'),
    path('registration_to_rebook_form/', views.registration_to_rebook_form, name='registration_to_rebook_form'),
    path('registration_to_rebook/', views.registration_to_rebook, name='registration_to_rebook'),

]

customer/models.py
from django.db import models

choose_gender = (
    ('Male', ' Male'), ('Female', 'Female'), ('Other', 'Other')
)


# Create your models here.

# Create your models here.
class Diet_Plan_Package(models.Model):
    package_name = models.CharField(max_length=555, unique=True)
    package_cost = models.CharField(max_length=555, unique=True)
    package_service = models.CharField(max_length=555, unique=True)

    package_visibility = models.BooleanField(default=True)
    package_validity = models.BooleanField(default=True)

    package_validity_time = models.CharField(max_length=555)

    # package_validity_time_start = models.DateField(null=True, blank=True)
    # package_validity_time_end = models.DateField(null=True, blank=True)
    # therapy_package_validity_time_start = models.DateField(null=True, blank=True)
    # therapy_package_validity_time_end =  models.DateField(null=True, blank=True)
    # gym_package_validity_time_start =  models.DateField(null=True, blank=True)
    # gym_package_validity_time_end = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.package_name


class Customer(models.Model):
    name = models.CharField(max_length=500, blank=True, default='')
    contact_person = models.CharField(max_length=500, blank=True, default='')

    age = models.CharField(max_length=100, blank=True, default='')
    gender = models.CharField(max_length=100, choices=choose_gender, blank=True, default='')
    date_of_birth = models.CharField(max_length=100, blank=True, default='')
    profession = models.CharField(max_length=100, blank=True, default='')

    address = models.CharField(max_length=100, blank=True, default='')
    landmark = models.CharField(max_length=100, blank=True, default='')
    city = models.CharField(max_length=100, blank=True, default='')
    state = models.CharField(max_length=100, blank=True, default='')
    country = models.CharField(max_length=100, blank=True, default='')

    contact_number = models.CharField(max_length=500, blank=True, default='')
    phone_number = models.CharField(max_length=500, blank=True, default='')
    social_number = models.CharField(max_length=500, blank=True, default='')
    email = models.CharField(max_length=500, blank=True, default='')

    annual_income = models.CharField(max_length=500, blank=True, default='')

    website = models.CharField(max_length=100, blank=True, default='')
    note = models.CharField(max_length=500, blank=True, default='')

    diet_plan = models.ForeignKey(Diet_Plan_Package, on_delete=models.DO_NOTHING, null=True, blank=True)

    # for clients
    tag = models.CharField(max_length=100, blank=True, default='')

    trashed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Customer_Stats(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING, blank=True, default='')
    weight = models.CharField(max_length=100, null=True, blank=True, default='')
    height = models.CharField(max_length=100, null=True, blank=True, default='')
    waist = models.CharField(max_length=100, null=True, blank=True, default='')
    hip = models.CharField(max_length=100, null=True, blank=True, default='')
    bmi = models.FloatField(max_length=100, null=True, blank=True, default='')
    whr = models.FloatField(max_length=100, null=True, blank=True, default='')
    entry_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    remark = models.CharField(max_length=100, null=True, blank=True, default='')

    def __str__(self):
        return self.customer.name

customer/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from django.shortcuts import render, redirect

from customer.form import CustomerForm, PackageForm
from customer.models import Diet_Plan_Package, Customer, Customer_Stats
from customer.serializers import Diet_Plan_Package_Serializer, Customer_Serializer
from diet.models import LogBook, DietPlan
from inquiry.models import Inquiry
from registration.models import Registration


# Create your views here.

def customer_list(request):
    context = {
        'customers': Customer.objects.filter(trashed=False),
    }
    return render(request, 'customer/customer_list.html', context)


import json


def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    inquiry = Inquiry.objects.all().filter(customer_name=customer)
    print(Inquiry.objects.filter(customer_name__pk=customer.pk))

    log_entries = LogBook.objects.filter(client_id=customer).order_by('date')
    dates = [entry.date.strftime('%Y-%m-%d') for entry in log_entries]
    before_weights = [entry.before_weight for entry in log_entries]
    after_weights = [entry.after_weight for entry in log_entries]
    print(dates)
    print(before_weights)
    print(after_weights)
    context = {
        'customer': customer,
        'inquiry': inquiry,
        'customer_stats': Customer_Stats.objects.filter(customer=customer),
        'registration': Registration.objects.filter(customer=customer),
        'logbook_entries': LogBook.objects.filter(client=customer),
        'diet_plan': DietPlan.objects.filter(customer=customer),
        'dates': json.dumps(dates),
        'beforeWeights': json.dumps(before_weights),
        'afterWeights': json.dumps(after_weights),

    }
    return render(request, 'customer/customer_detail.html', context)


def add_customer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('customer:customer_list')
        else:
            # Handle the error
            print(form.errors)
    else:
        form = CustomerForm()
    return render(request, 'customer/add_customer.html', {'form': form})


def edit_customer(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customer:customer_list')
        else:
            # Handle the error
            print(form.errors)
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'customer/edit_customer.html', {'form': form, 'customer': customer})


def trash_customer(request):
    customer = get_object_or_404(Customer, pk=request.POST.get("trash_id"))
    customer.trashed = True
    customer.save()
    return redirect('customer:customer_list')


class DietPlanAPI(APIView):

    def get(self, request, format=None):
        notification = Diet_Plan_Package.objects.all()
        serializer = Diet_Plan_Package_Serializer(notification, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = Diet_Plan_Package_Serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DietPlanDetails(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """

    def get_object(self, pk):
        try:
            return Diet_Plan_Package.objects.get(pk=pk)
        except Diet_Plan_Package.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = Diet_Plan_Package_Serializer(snippet)
        return Response(serializer.data)

    '''def put(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = Diet_Plan_Package_Serializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)'''


class CustomerAPI(APIView):

    def get(self, request, format=None):
        customer = Customer.objects.all()
        serializer = Customer_Serializer(customer, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = Customer_Serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CustomerDetails(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """

    def get_object(self, pk):
        try:
            return Customer.objects.get(pk=pk)
        except Customer.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = Customer(snippet)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = Customer_Serializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def vidhyas_package(request, pk=None):
    if pk:
        diet_Plan_Package = get_object_or_404(Diet_Plan_Package, pk=pk)
    else:
        diet_Plan_Package = None

    if request.method == 'POST':
        if diet_Plan_Package:
            form = PackageForm(request.POST, instance=diet_Plan_Package)
        else:
            form = PackageForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('customer:vidhyas_package')
        else:
            print(form.errors)
    else:
        form = PackageForm(instance=diet_Plan_Package) if diet_Plan_Package else PackageForm()

    diet_Plan_Package = Diet_Plan_Package.objects.all()
    return render(request, 'customer/vidhyas_package/vidhyas_package.html',
                  {'form': form, 'diet_Plan_Package': diet_Plan_Package})


def delete_vidhyas_package(request):
    diet_Plan_Package = get_object_or_404(Diet_Plan_Package, pk=request.POST.get('trash_id'))
    diet_Plan_Package.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/customer/customer_base.html
{% extends 'base.html' %}
{% load static %}
{% block top-menu-content %}

    {% comment %}  <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
    </li>{% endcomment %}
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'customer:customer_list' %}" class="nav-link">Customer List</a>
    </li>
     <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'customer:add_customer' %}" class="nav-link">Add New Customer </a>
    </li>

{% endblock top-menu-content %}

{% block content %}
    {% block sub-content %}

    {% endblock sub-content %}

{% endblock content %}

templates/customer/customer_list.html
{% extends 'customer/customer_base.html' %}
{% load static %}
{% block page_css %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/select.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/dataTables.dataTables.css' %}">
    <style>
        .dataTables_wrapper .top {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
        }

        .dataTables_wrapper .bottom {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
        }

        .dataTables_wrapper .dataTables_length,
        .dataTables_wrapper .dataTables_filter {
            margin: 0;
        }

        .dataTables_wrapper .dt-buttons {
            margin-left: auto;
        }

        .dataTables_wrapper .dataTables_paginate,
        .dataTables_wrapper .dataTables_info {
            margin: 0;
        }


    </style>
{% endblock page_css %}

{% block sub-content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Customer List</h3>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="dtable" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Contact</th>
                                    <th>Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for customer in customers reversed %}
                                    <tr>

                                        <td></td>
                                        <td>{{ customer.name }} </td>
                                        <td>{{ customer.address }}</td>
                                        <td>{{ customer.contact_number }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button"
                                                        class="btn btn-block btn-outline-secondary dropdown-toggle"
                                                        data-toggle="dropdown">Action
                                                </button>

                                                <div class="dropdown-menu" role="menu">
                                                    <a class="dropdown-item"
                                                       href="{% url 'customer:customer_detail' customer.id %}">Details</a>
                                                    <a class="dropdown-item"
                                                       href="{% url 'customer:edit_customer' customer.id %}">Edit</a>
                                                    <a class="dropdown-item" href="#"
                                                       data-toggle="modal"
                                                       data-target="#trash_transaction"
                                                       data-id="{{ customer.id }}">Trash

                                                    </a>
                                                    <a class="dropdown-item"
                                                       href="{% url 'diet:create_diet_plan_new' customer.id %}">Create
                                                        Diet Chart</a>

                                                    {% comment %}  <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item"
                                                       href="{% url 'registration:inquiry_to_registration_form' %}?id={{ inquiry.id }}">Register
                                                        to Client</a>{% endcomment %}

                                                </div>
                                            </div>

                                        </td>

                                    </tr>

                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Contact</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>


                    </div>

                </div>
            </div>

        </div>
    </section>

    <div class="modal fade" id="trash_transaction">
        <div class="modal-dialog">
            <div class="modal-content bg-danger">
                <div class="modal-header">
                    <h4 class="modal-title">Trash Inquiry</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form-horizontal" action="{% url 'customer:trash_customer' %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="trash_id"> </label><input type="text" hidden class="form-control" id="trash_id"
                                                              name="trash_id">
                    </div>

                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-light">Move To Trash</button>
                    </div>
                </form>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

{% endblock sub-content %}
{% block page_script %}
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

    <script src="{% static 'plugins/datatables-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-select/js/select.bootstrap4.min.js' %}"></script>
    <script>

        $(document).ready(function () {
            var table = $('#dtable').DataTable({
                lengthMenu: [10, 20, 50, 100],
                responsive: true, lengthChange: false, autoWidth: false,
                columnDefs: [
                    {
                        orderable: false,
                        className: 'select-checkbox',
                        targets: 0
                    }
                ],
                select: {
                    style: 'multi',
                    selector: 'td:first-child'
                },
                order: [[1, 'asc']],
                dom: '<"top"fB>rt<"bottom"ilp><"clear">',
                buttons: [
                    {
                        text: 'Delete Selected',
                        className: 'btn btn-primary delete-selected',
                        action: function () {
                            var selectedRows = table.rows({selected: true}).data();
                            var ids = [];
                            for (var i = 0; i < selectedRows.length; i++) {
                                ids.push(selectedRows[i][1]); // Assuming the ID is in the second column
                            }
                            if (ids.length > 0) {
                                // Implement your delete logic here
                                console.log('Delete these IDs:', ids);
                                // Example: Make an AJAX call to delete
                                // $.post('/delete-url/', { ids: ids }, function(response) {
                                //     table.rows('.selected').remove().draw(false);
                                // });
                            } else {
                                alert('No rows selected');
                            }
                        },
                        enabled: false
                    },
                    {
                        extend: 'collection',
                        text: 'Export',
                        className: 'btn btn-primary',
                        buttons: [
                            {
                                extend: 'copy',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'csv',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'excel',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'pdf',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'print',
                                className: 'btn btn-primary'
                            }
                        ]
                    },
                    {
                        extend: 'colvis',
                        className: 'btn btn-primary'
                    }, {
                        extend: 'collection',
                        text: 'Table Info',
                        className: 'btn btn-primary',
                        buttons: [
                            {
                                extend: 'colvisGroup',
                                text: 'Customer info',
                                show: [2, 3, 4, 5, 8],
                                hide: [1, 6, 7]
                            },
                            {
                                extend: 'colvisGroup',
                                text: 'Inquiry info',
                                show: [1, 2, 6, 7, 8],
                                hide: [4, 5]
                            },
                            {
                                extend: 'colvisGroup',
                                text: 'Show all',
                                show: ':hidden'
                            },

                        ]
                    },
                ]
            });

            table.on('select deselect', function () {
                var selectedRows = table.rows({selected: true}).count();
                table.button(0).enable(selectedRows > 0);
                if (selectedRows > 0) {
                    $('.delete-selected').show();
                } else {
                    $('.delete-selected').hide();
                }
            });

            // Initially hide the "Delete Selected" button
            $('.delete-selected').hide();
        });


    </script>
    <script>
        $(function () {
            $('#trash_transaction').on('show.bs.modal', function (event) {
                document.getElementById("trash_id").value = $(event.relatedTarget).data('id');
            });
        });
    </script>
{% endblock page_script %}