VidhyasDietERP/urls.py
from django.urls import path, include

from django.contrib import admin
# from vidhyas_api.views import ObtainAuthTokenView

urlpatterns = [
    path('admin/', admin.site.urls),            # default admin
    path('api/', include("vidhyas_api.urls")),  # include api
    path('', include("user_authentication.urls")),   # include auth
    path('', include("customer.urls")),   # include auth
    path('', include("humanresource.urls")),   # include auth
    path('', include('index.urls')),             # include index
    path('', include('inquiry.urls')),             # include inquiry
    path('', include('registration.urls')),             # include registration
    path('', include('account.urls')),             # include account_list
    path('', include('diet.urls')),             # include diet
    path('', include('todo.urls')),             # include diet
]

customer/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from customer.views import (DietPlanAPI, DietPlanDetails, CustomerAPI, CustomerDetails, customer_list, add_customer,
                            edit_customer, trash_customer, customer_detail, vidhyas_package, delete_vidhyas_package)

app_name = 'customer'

urlpatterns = [

    path('api/diet_plan', DietPlanAPI.as_view(), name='DietPlanAPI'),
    path('api/diet_plan/<int:pk>', DietPlanDetails.as_view(), name='DietPlanDetailsApi'),
    path('api/customer', CustomerAPI.as_view(), name='CustomerAPI'),
    path('api/customer/<int:pk>', CustomerDetails.as_view(), name='CustomerDetailsApi'),

    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer_list/', customer_list, name='customer_list'),
    path('add_customer/', add_customer, name='add_customer'),
    path('edit_customer/<int:pk>/', edit_customer, name='edit_customer'),
    path('trash_customer/', trash_customer, name='trash_customer'),
    path('vidhyas_package/', vidhyas_package, name='vidhyas_package'),
    path('vidhyas_package/<int:pk>', vidhyas_package, name='edit_vidhyas_package'),
    path('delete_vidhyas_package/', delete_vidhyas_package, name='delete_vidhyas_package'),
]

diet/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from diet.views import (create_logbook_and_stats, body_composition, create_diet_plan_new, create_diet_plan,
                        edit_diet_plan, diet_plan_list, diet_plan_print_nepali, diet_plan_print_english,
                        diet_plan_trash, diet_plan_preview,chart)

app_name = 'diet'

urlpatterns = [
    path('create_logbook_and_stats/', create_logbook_and_stats, name='create_logbook_and_stats'),
    path('create_logbook_and_stats/<int:pk>/', create_logbook_and_stats, name='edit_logbook_and_stats'),

    path('bmi/', body_composition, name='bmi'),
    path('bmi/<int:pk>/', body_composition, name='edit_bmi'),

    # path('diet_plan/', create_or_edit_diet_plan, name='create_diet_plan'),
    # path('diet_plan/<int:pk>/', create_or_edit_diet_plan, name='edit_diet_plan'),

    path('diet_plan_preview/<int:pk>/', diet_plan_preview, name='diet_plan_preview'),
    path('create_diet_plan_new/', create_diet_plan, name='create_diet_plan'),
    path('diet_plan/<int:pk>/edit/', edit_diet_plan, name='edit_diet_plan'),
    path('diet_plan/new/<int:customer_id_pk>/', create_diet_plan_new, name='create_diet_plan_new'),
    path('diet_plan_list/', diet_plan_list, name='diet_plan_list'),
    path('diet_plan_print_nepali/<int:pk>/', diet_plan_print_nepali, name='diet_plan_print_nepali'),
    path('diet_plan_print_english/<int:pk>/', diet_plan_print_english, name='diet_plan_print_english'),
    path('diet_plan_trash/', diet_plan_trash, name='diet_plan_trash'),


    path('chart/<int:client_id>/', chart, name='chart'),

]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),

]

inquiry/urls.py
from django.urls import path
from inquiry import views

app_name = 'inquiry'

urlpatterns = [
    path('inquiry_list/', views.inquiry_list, name='inquiry_list'),
    path('add_inquiry_form/', views.add_inquiry_form, name='add_inquiry_form'),
    path('add_inquiry/', views.add_inquiry, name='add_inquiry'),
    path('edit_inquiry_form/', views.edit_inquiry_form, name='edit_inquiry_form'),
    path('edit_inquiry/', views.edit_inquiry, name='edit_inquiry'),
    path('trash_inquiry/', views.trash_inquiry, name='trash_inquiry'),
    path('details_inquiry/', views.details_inquiry, name='details_inquiry'),

]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('toggle/<int:todo_id>/', views.toggle_completed, name='toggle_completed'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('trash/<int:todo_id>/', views.trash_todo, name='trash_todo'),
]

templates/index/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_css %}

{% endblock page_css %}
{% block top-menu-content %}

    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index:index' %}" class="nav-link">Dashboard</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'inquiry:inquiry_list' %}" class="nav-link">Inquiry</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'customer:customer_list' %}" class="nav-link">Customer</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'humanresource:employee_list' %}" class="nav-link">Employee</a>
    </li>
{% endblock %}
{% block content %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Dashboard</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
        <div class="container-fluid">



            <div class="row">

                <section class="col-lg-7"><div class="row">
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>0</h3>

                            <p>New INQUIRY</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="{% url 'inquiry:inquiry_list' %}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>0<sup style="font-size: 20px"></sup></h3>

                            <p>Registration</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="{% url 'registration:registration_list' %}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>0</h3>

                            <p>Customer</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{% url 'customer:customer_list' %}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>65</h3>

                            <p>Unique Visitors</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>  </section>
            <section class="col-lg-5 ">
      <!-- Calendar -->
                <div class="card ">
                    <div class="card-header border-0">

                        <h3 class="card-title">
                            <i class="far fa-calendar-alt"></i>
                            Calendar
                        </h3>
                        <!-- tools card -->
                        <div class="card-tools">
                            <!-- button with a dropdown -->
                            <button type="button" class="btn btn-secondary btn-sm" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            {% comment %} <button type="button" class="btn btn-success btn-sm" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>{% endcomment %}
                        </div>
                        <!-- /. tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body pt-0">
                        <!--The calendar -->
                        <div id="" style="width: 100%">
                            <script type="text/javascript">

                                var nc_width = 'responsive';
                                var nc_height = 220;
                                var nc_api_id = 5872024073669;
                            </script>
                            <script type="text/javascript" src="https://www.ashesh.com.np/calendarlink/nc.js"></script>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </section></div>
             <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="ion ion-clipboard mr-1"></i>
                        To Do List
                    </h3>
                      <!-- tools card -->
                <div class="card-tools">
                  <!-- button with a dropdown -->
                  <div class="btn-group">


                  </div>
                  <button type="button" class="btn btn-secondary btn-sm" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-secondary btn-sm" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div> </div>
                <!-- /. tools -->

                <!-- /.card-header -->
                <div class="card-body">
                    <ul id="todo-list" class="todo-list" data-widget="todo-list">
                        {% for todo in todos %}
                            <li id="todo-card-{{ todo.id }}">
                        <span class="handle">
                            <i class="fas fa-ellipsis-v"></i>
                            <i class="fas fa-ellipsis-v"></i>
                        </span>
                                <div class="icheck-primary d-inline ml-2">
                                    <input type="checkbox" value="" name="todo{{ todo.id }}" id="todoCheck{{ todo.id }}"
                                           {% if todo.completed %}checked{% endif %}
                                           onclick="toggleCompleted({{ todo.id }})">
                                    <label for="todoCheck{{ todo.id }}"></label>
                                </div>
                                <span class="text">{{ todo.title }}</span>
                                <div class="tools">
                                    <i class="fas fa-trash" onclick="trashTodoItem({{ todo.id }})"></i>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                    <form id="add-todo-form">
                        <div class="input-group">
                            <input type="text" id="todo-title" name="title" class="form-control"
                                   placeholder="Add new to-do">
                            <span class="input-group-append">
                            <button type="submit" class="btn btn-secondary"><i class="fas fa-plus"></i> Add item</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

{% block page_script %}
<script>
    function toggleCompleted(todoId) {
        $.ajax({
            url: `/toggle/${todoId}/`,
            method: 'GET',
            success: function(data) {
                if (data.success) {
                    const item = $(`#todo-card-${todoId}`);
                    item.toggleClass('completed', data.completed);
                }
            }
        });
    }

    function trashTodoItem(todoId) {
        $.ajax({
            url: `/trash/${todoId}/`,
            method: 'GET',
            success: function(data) {
                if (data.success) {
                    $(`#todo-card-${todoId}`).remove();
                }
            }
        });
    }

    $('#add-todo-form').on('submit', function(event) {
        event.preventDefault();
        const title = $('#todo-title').val();
        $.ajax({
            url: `{% url 'todo:add_todo' %}`,
            method: 'POST',
            data: {
                'title': title,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
                if (data.success) {
                    const newItem = `
                        <li id="todo-card-${data.id}" class="${data.completed ? 'completed' : ''}">
                            <span class="handle">
                                <i class="fas fa-ellipsis-v"></i>
                                <i class="fas fa-ellipsis-v"></i>
                            </span>
                            <div class="icheck-primary d-inline ml-2">
                                <input type="checkbox" value="" name="todo${data.id}" id="todoCheck${data.id}" onclick="toggleCompleted(${data.id})">
                                <label for="todoCheck${data.id}"></label>
                            </div>
                            <span class="text">${data.title}</span>
                            <div class="tools">
                                <i class="fas fa-trash" onclick="trashTodoItem(${data.id})"></i>
                            </div>
                        </li>`;
                    $('#todo-list').append(newItem);
                    $('#todo-title').val('');  // Clear the input field
                }
            }
        });
    });
</script>

{% endblock page_script %}

templates/index/test.html
{% extends 'base.html' %}
{% load static %}

{% block page_css %}
<style>

</style>
{% endblock page_css %}

{% block content %}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Test Application</h1>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <!-- TO DO List -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="ion ion-clipboard mr-1"></i>
                    To Do List
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <ul id="todo-list" class="todo-list" data-widget="todo-list">
                    {% for todo in todos %}
                    <li id="todo-card-{{ todo.id }}">
                        <span class="handle">
                            <i class="fas fa-ellipsis-v"></i>
                            <i class="fas fa-ellipsis-v"></i>
                        </span>
                        <div class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo{{ todo.id }}" id="todoCheck{{ todo.id }}" {% if todo.completed %}checked{% endif %} onclick="toggleCompleted({{ todo.id }})">
                            <label for="todoCheck{{ todo.id }}"></label>
                        </div>
                        <span class="text">{{ todo.title }}</span>
                        <div class="tools">
                            <i class="fas fa-trash" onclick="trashTodoItem({{ todo.id }})"></i>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                <form id="add-todo-form">
                    <div class="input-group">
                        <input type="text" id="todo-title" name="title" class="form-control" placeholder="Add new to-do">
                        <span class="input-group-append">
                            <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i> Add item</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block page_script %}
<script>
    function toggleCompleted(todoId) {
        $.ajax({
            url: `/toggle/${todoId}/`,
            method: 'GET',
            success: function(data) {
                if (data.success) {
                    const item = $(`#todo-card-${todoId}`);
                    item.toggleClass('completed', data.completed);
                }
            }
        });
    }

    function trashTodoItem(todoId) {
        $.ajax({
            url: `/trash/${todoId}/`,
            method: 'GET',
            success: function(data) {
                if (data.success) {
                    $(`#todo-card-${todoId}`).remove();
                }
            }
        });
    }

    $('#add-todo-form').on('submit', function(event) {
        event.preventDefault();
        const title = $('#todo-title').val();
        $.ajax({
            url: `{% url 'todo:add_todo' %}`,
            method: 'POST',
            data: {
                'title': title,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
                if (data.success) {
                    const newItem = `
                        <li id="todo-card-${data.id}" class="${data.completed ? 'completed' : ''}">
                            <span class="handle">
                                <i class="fas fa-ellipsis-v"></i>
                                <i class="fas fa-ellipsis-v"></i>
                            </span>
                            <div class="icheck-primary d-inline ml-2">
                                <input type="checkbox" value="" name="todo${data.id}" id="todoCheck${data.id}" onclick="toggleCompleted(${data.id})">
                                <label for="todoCheck${data.id}"></label>
                            </div>
                            <span class="text">${data.title}</span>
                            <div class="tools">
                                <i class="fas fa-trash" onclick="trashTodoItem(${data.id})"></i>
                            </div>
                        </li>`;
                    $('#todo-list').append(newItem);
                    $('#todo-title').val('');  // Clear the input field
                }
            }
        });
    });
</script>
{% endblock %}