VidhyasDietERP/urls.py
from django.urls import path, include

from django.contrib import admin
# from vidhyas_api.views import ObtainAuthTokenView

urlpatterns = [
    path('admin/', admin.site.urls),            # default admin
    path('api/', include("vidhyas_api.urls")),  # include api
    path('', include("user_authentication.urls")),   # include auth
    path('', include("customer.urls")),   # include auth
    path('', include("humanresource.urls")),   # include auth
    path('', include('index.urls')),             # include index
    path('', include('inquiry.urls')),             # include inquiry
    path('', include('registration.urls')),             # include registration
    path('', include('account.urls')),             # include account_list
    path('', include('diet.urls')),             # include diet
    path('', include('todo.urls')),             # include diet
]

account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [

    path('account_list', views.account_list, name='account_list'),
]

customer/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from customer.views import (DietPlanAPI, DietPlanDetails, CustomerAPI, CustomerDetails, customer_list, add_customer,
                            edit_customer, trash_customer, customer_detail, vidhyas_package, delete_vidhyas_package)

app_name = 'customer'

urlpatterns = [

    path('api/diet_plan', DietPlanAPI.as_view(), name='DietPlanAPI'),
    path('api/diet_plan/<int:pk>', DietPlanDetails.as_view(), name='DietPlanDetailsApi'),
    path('api/customer', CustomerAPI.as_view(), name='CustomerAPI'),
    path('api/customer/<int:pk>', CustomerDetails.as_view(), name='CustomerDetailsApi'),

    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer_list/', customer_list, name='customer_list'),
    path('add_customer/', add_customer, name='add_customer'),
    path('edit_customer/<int:pk>/', edit_customer, name='edit_customer'),
    path('trash_customer/', trash_customer, name='trash_customer'),
    path('vidhyas_package/', vidhyas_package, name='vidhyas_package'),
    path('vidhyas_package/<int:pk>', vidhyas_package, name='edit_vidhyas_package'),
    path('delete_vidhyas_package/', delete_vidhyas_package, name='delete_vidhyas_package'),
]

diet/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from diet.views import (create_logbook_and_stats, body_composition, create_diet_plan_new, create_diet_plan,
                        edit_diet_plan, diet_plan_list, diet_plan_print_nepali, diet_plan_print_english,
                        diet_plan_trash, diet_plan_preview,chart)

app_name = 'diet'

urlpatterns = [
    path('create_logbook_and_stats/', create_logbook_and_stats, name='create_logbook_and_stats'),
    path('create_logbook_and_stats/<int:pk>/', create_logbook_and_stats, name='edit_logbook_and_stats'),

    path('bmi/', body_composition, name='bmi'),
    path('bmi/<int:pk>/', body_composition, name='edit_bmi'),

    # path('diet_plan/', create_or_edit_diet_plan, name='create_diet_plan'),
    # path('diet_plan/<int:pk>/', create_or_edit_diet_plan, name='edit_diet_plan'),

    path('diet_plan_preview/<int:pk>/', diet_plan_preview, name='diet_plan_preview'),
    path('create_diet_plan_new/', create_diet_plan, name='create_diet_plan'),
    path('diet_plan/<int:pk>/edit/', edit_diet_plan, name='edit_diet_plan'),
    path('diet_plan/new/<int:customer_id_pk>/', create_diet_plan_new, name='create_diet_plan_new'),
    path('diet_plan_list/', diet_plan_list, name='diet_plan_list'),
    path('diet_plan_print_nepali/<int:pk>/', diet_plan_print_nepali, name='diet_plan_print_nepali'),
    path('diet_plan_print_english/<int:pk>/', diet_plan_print_english, name='diet_plan_print_english'),
    path('diet_plan_trash/', diet_plan_trash, name='diet_plan_trash'),


    path('chart/<int:client_id>/', chart, name='chart'),

]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),

]

inquiry/urls.py
from django.urls import path
from inquiry import views

app_name = 'inquiry'

urlpatterns = [
    path('inquiry_list/', views.inquiry_list, name='inquiry_list'),
    path('add_inquiry_form/', views.add_inquiry_form, name='add_inquiry_form'),
    path('add_inquiry/', views.add_inquiry, name='add_inquiry'),
    path('edit_inquiry_form/', views.edit_inquiry_form, name='edit_inquiry_form'),
    path('edit_inquiry/', views.edit_inquiry, name='edit_inquiry'),
    path('trash_inquiry/', views.trash_inquiry, name='trash_inquiry'),
    path('details_inquiry/', views.details_inquiry, name='details_inquiry'),

]

templates/VidhyasDietPlanEnglish.html
<!DOCTYPE  html >
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="author" content="user"/>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        #page-size-div {
            size: 21cm 29.7cm;
            position: relative;

        }

        header {
            display: flex;
            justify-content: space-between;
            align-items: center;

        }

        header .logo {
            width: 100%;
        }

        .container-page {
            margin-left: 30px;
            margin-right: 30px;
        }

        h1 {
            font-size: 18px;
            margin: 0;
            text-align: center;
        }

        h2 {
            font-size: 16px;
            margin: 0;
            text-align: center;
            font-weight: normal;
        }


        h3 {
            font-size: 18px;
            margin: 0;

        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 2px;

        }

        th, td {
            border: 1px solid #000;
            padding-left: 10px;

        }

        tr {
            text-align: left;
        }

        th {
            text-align: left;
        }

        .top-table td {
            text-align: center;
        }

        .top-table th {
            text-align: center;
        }

        .left-table {
            width: 85%;
            border-collapse: collapse;
            margin-bottom: 2px;
            margin-top: 5px;

        }


        .left-table th {
            width: 45%;
        }


        .right-content {
            padding-top: 50px;
        }

        .right-table td {
            border: none;
            width: 50%;
        }

        .right-table th {
            border: none;
            width: 50%;
            padding-top: 20px;
        }


        .selly-row {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;


        }

        .col-md-8 {
            -ms-flex: 0 0 66.666667%;
            flex: 0 0 66.666667%;
            max-width: 66.666667%;
        }

        .col-md-4 {
            -ms-flex: 0 0 33.333333%;
            flex: 0 0 33.333333%;
            max-width: 33.333333%;
        }
    </style>
    <style>
        #page1-div {

        }


        @media print {
            * {
                -webkit-print-color-adjust: exact !important; /*Chrome, Safari */
                color-adjust: exact !important; /*Firefox*/
            }
        }
    </style>
    <script type="text/javascript">
        alert("Note for printing or exporting system created registration form: \n" +
            "\n" +
            "Please print or export in A4 Size with margins 'None' for right formant");
    </script>
</head>
<body>
<div id="page-size-div" style="">
    <header>
        <img src="/../static/dist/img/company/letterhead.jpeg" alt="Logo" class="logo">
    </header>
    <div class="container-page">
        <h1>Diet Plan Chart</h1>
        <h2>Food groups served for Customer</h2>
        <table class="top-table">
            <thead>
            <tr>
                <th>Cereals, Pulses,<br>Starched and Legumes</th>
                <th>Vegetables</th>
                <th>Fruits</th>
                <th>Meet Egg and <br>other substitutes</th>
                <th>Milk and its Product</th>
                <th>Fat oil and its Product</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>1</td>
                <td>1</td>
                <td>1</td>
                <td>1</td>
            </tr>
            </tbody>
        </table>
        <div class="selly-row">
            <div class="col-md-8">

                <table class="left-table">
                    <thead>
                    <tr>
                        <th>BreakFast</th>
                        <td>6:30 AM</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Chapatti
                            (wheat, maize, buckwheat, finger millet )
                        </td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Dry Bread :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Rolled oats / Other cereals :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Boiled/Fried EGG :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Boiled Vegetables :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>
                <table class="left-table">
                    <thead>
                    <tr>
                        <th>Mid Morning Snacks</th>
                        <td>6:30 AM</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Cut Fruits</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Yogurt/curd/Buttermilk :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>
                <table class="left-table">
                    <thead>
                    <tr>
                        <th>Lunch</th>
                        <td>6:30 AM</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Rice/Dhindo/chakla :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Sukka Roti :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Lentils/Pulses :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Vegetables curry :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Leafy/Raw vegetables :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Meat/Tofu/Paneer :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Fish (palm size) :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>
                <table class="left-table">
                    <thead>
                    <tr>
                        <th>Afternoon Snack</th>
                        <td>6:30 AM</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Sandwich :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Dry Bread/Bread Roll :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Beaten rice :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Roasted/Puffed Corn :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Pulses :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Raw vegetables :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>

            </div>
            <div class=" right-content col-md-4">
                <h3>Calories and grams <br> of a day</h3>
                <table class="right-table" style="">
                    <thead>
                    <tr>
                        <th><u> Carbohydrates</u></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td> Calories:</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Grams:</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                    <thead>
                    <tr>
                        <th><u>Proteins</u></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td> Calories :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Grams :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                    <thead>
                    <tr>
                        <th><u>Fat</u></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Calories :</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Grams :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td style="padding-top: 25px">Total Calories :</td>
                        <td style="padding-top: 25px">1</td>
                    </tr>
                    <tr>
                        <td>Activity Level :</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>
                <h3 style="margin-top: 20px">Remarks:</h3>
                <h4></h4>
            </div>
        </div>
        <div class="selly-row">
            <div class="col-md-8">
                <table class="left-table">

                    <thead>
                    <tr>
                        <th>Dinner</th>
                        <td>6:30 AM</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Rice/Dhindo/Chakla</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Dry Bread</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Lentils/Pulses</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Vegetables</td>
                        <td>1</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class=" col-md-4">
                <h3>Created Date : 2024/6/2</h3>
                <h3>Day : EveryDay</h3>
                <h3>Created By : Vidhya R. Kayastha</h3>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidhyas Diet </title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    {% block page_css %}

    {% endblock page_css %}

    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
</head>
<body class="hold-transition sidebar-mini sidebar-collapse layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            {% block top-menu-content %}
            {% endblock top-menu-content %}
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="sign-out" href="{% url 'user_authentication:login' %}" role="button">
                    <i class="fa fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'index:index' %}" class="brand-link">
            {% comment %} <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">{% endcomment %}
            <span class="brand-text font-weight-light">Vidhyas Diet</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{% url 'inquiry:inquiry_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Inquiry

                            </p>
                        </a>

                    </li>
                     <li class="nav-item">
                        <a href="{% url 'registration:registration_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Registration

                            </p>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a href="{% url 'humanresource:employee_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                Employee

                            </p>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a href="{% url 'customer:customer_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-user-friends"></i>
                            <p>
                                Customer

                            </p>
                        </a>

                    </li>
                       <li class="nav-item">
                        <a href="{% url 'customer:vidhyas_package' %}" class="nav-link">
                            <i class="nav-icon fas fa-folder"></i>
                            <p>
                                Vidhyas Package

                            </p>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a href="{% url 'diet:create_logbook_and_stats' %}" class="nav-link">
                            <i class="nav-icon fas fa-book"></i>
                            <p>
                                Diet

                            </p>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:account_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-dollar-sign"></i>
                            <p>
                                Account

                            </p>
                        </a>

                    </li>


                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        {% block content %}





        {% endblock content %}
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script type="text/javascript" src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script type="text/javascript" src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- Bootstrap 4 -->
<script type="text/javascript" src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% comment %}
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
{% endcomment %}
<!-- overlayScrollbars -->
<script type="text/javascript"
        src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script type="text/javascript" src="{% static 'dist/js/adminlte.js' %}"></script>


{% block page_script %}

{% endblock page_script %}

</body>
</html>

templates/datatable_template.html
{% block page_css %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/select.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-select/css/dataTables.dataTables.css' %}">
    <style>
        .dataTables_wrapper .top {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
        }

        .dataTables_wrapper .bottom {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
        }

        .dataTables_wrapper .dataTables_length,
        .dataTables_wrapper .dataTables_filter {
            margin: 0;
        }

        .dataTables_wrapper .dt-buttons {
            margin-left: auto;
        }

        .dataTables_wrapper .dataTables_paginate,
        .dataTables_wrapper .dataTables_info {
            margin: 0;
        }


    </style>
{% endblock page_css %}


{% block page_script %}
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

    <script src="{% static 'plugins/datatables-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-select/js/select.bootstrap4.min.js' %}"></script>
    <script>

        $(document).ready(function () {
            var table = $('#dtable').DataTable({
                lengthMenu: [10, 20, 50, 100],
                responsive: true, lengthChange: false, autoWidth: false,
                columnDefs: [
                    {
                        orderable: false,
                        className: 'select-checkbox',
                        targets: 0
                    }
                ],
                select: {
                    style: 'multi',
                    selector: 'td:first-child'
                },
                order: [[1, 'asc']],
                dom: '<"top"fB>rt<"bottom"ilp><"clear">',
                buttons: [
                    {
                        text: 'Delete Selected',
                        className: 'btn btn-primary delete-selected',
                        action: function () {
                            var selectedRows = table.rows({selected: true}).data();
                            var ids = [];
                            for (var i = 0; i < selectedRows.length; i++) {
                                ids.push(selectedRows[i][1]); // Assuming the ID is in the second column
                            }
                            if (ids.length > 0) {
                                // Implement your delete logic here
                                console.log('Delete these IDs:', ids);
                                // Example: Make an AJAX call to delete
                                // $.post('/delete-url/', { ids: ids }, function(response) {
                                //     table.rows('.selected').remove().draw(false);
                                // });
                            } else {
                                alert('No rows selected');
                            }
                        },
                        enabled: false
                    },
                    {
                        extend: 'collection',
                        text: 'Export',
                        className: 'btn btn-primary',
                        buttons: [
                            {
                                extend: 'copy',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'csv',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'excel',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'pdf',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'print',
                                className: 'btn btn-primary'
                            }
                        ]
                    },
                    {
                        extend: 'colvis',
                        className: 'btn btn-primary'
                    }, {
                        extend: 'collection',
                        text: 'Table Info',
                        className: 'btn btn-primary',
                        buttons: [
                            {
                                extend: 'colvisGroup',
                                text: 'Customer info',
                                show: [2, 3, 4, 5, 8],
                                hide: [1, 6, 7]
                            },
                            {
                                extend: 'colvisGroup',
                                text: 'Inquiry info',
                                show: [1, 2, 6, 7, 8],
                                hide: [4, 5]
                            },
                            {
                                extend: 'colvisGroup',
                                text: 'Show all',
                                show: ':hidden'
                            },

                        ]
                    },
                ]
            });

            table.on('select deselect', function () {
                var selectedRows = table.rows({selected: true}).count();
                table.button(0).enable(selectedRows > 0);
                if (selectedRows > 0) {
                    $('.delete-selected').show();
                } else {
                    $('.delete-selected').hide();
                }
            });

            // Initially hide the "Delete Selected" button
            $('.delete-selected').hide();
        });


    </script>

{% endblock page_script %}